#!/bin/bash

if [ $# -eq 0 ]; then
  echo "Usage: $0 <port1> <port2> ..."
  exit 1
fi

for port in "$@"; do
  # ポート番号から複数のPIDを取得
  pids=$(lsof -t -i :$port)

  # 見つかったPIDがある場合、killコマンドを実行
  if [ -n "$pids" ]; then
    for pid in $pids; do
      echo "Killing process with PID: $pid on port $port"
      kill "$pid"
    done
  else
    echo "No process found on port $port"
  fi
done
